name: Sanjeeb first pipeline

on:
  push:
    branches:
      - main

jobs:
  myjobslinuxcmd: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Linux command
        run: |
          echo "Hello, GitHub Actions!"
          ls -la
          pwd
          mkdir sonziib
          ls -al
          